# Generated by Django 5.2.10 on 2026-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('phoneno', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('cv_url', models.CharField(max_length=200)),
                ('profile_url', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
