# Generated by Django 5.2.10 on 2026-02-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
