# Generated by Django 5.2.10 on 2026-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_job_company_job_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ig_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_meta_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
