# Generated by Django 5.2.10 on 2026-02-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_employee_fb_page_id_employee_ig_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='token_expires_at',
        ),
    ]
