# Generated by Django 5.2.10 on 2026-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_employee_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
