# Generated by Django 5.2.10 on 2026-02-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.user_detail'),
            preserve_default=False,
        ),
    ]
