# Generated by Django 5.2.10 on 2026-03-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_job_hr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_date', models.DateTimeField(blank=True, null=True)),
                ('machine_test_date', models.DateTimeField(blank=True, null=True)),
                ('hr_interview_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.job')),
            ],
        ),
    ]
