# Generated by Django 5.2.10 on 2026-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='machine_test_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mcq_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
