# Generated by Django 5.2.10 on 2026-03-12 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_application_machine_test_score_application_mcq_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprocess',
            name='interview_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='interview_room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='interview_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='not_started', max_length=20),
        ),
    ]
