# Generated by Django 5.2.10 on 2026-03-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_jobprocess_interview_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprocess',
            name='interview_ended_at',
        ),
    ]
