# Generated by Django 5.2.10 on 2026-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_application_hr_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
    ]
