# Generated by Django 5.2.10 on 2026-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_application_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('interview_completed', 'Interview Completed')], default='pending', max_length=20),
        ),
    ]
