# Generated by Django 5.2.10 on 2026-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
