# Generated by Django 5.2.10 on 2026-03-23 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_application_interview_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
