# Generated by Django 5.2.10 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_application_interview_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_recording',
            field=models.FileField(blank=True, null=True, upload_to='interview_recordings/'),
        ),
    ]
