# Generated by Django 5.2.10 on 2026-03-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_application_interview_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
