# Generated by Django 5.2.10 on 2026-04-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_application_interview_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_login_tokens', to='register.user_detail')),
            ],
        ),
    ]
