# Generated by Django 5.2.10 on 2026-03-01 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.PositiveIntegerField(db_index=True)),
                ('language', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('JS', 'JavaScript')], max_length=16)),
                ('code', models.TextField()),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('time_limit', 'Time Limit Exceeded'), ('error', 'Error')], max_length=20)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['problem_id', 'verdict'], name='m_test_subm_problem_d640d9_idx'), models.Index(fields=['user', 'problem_id'], name='m_test_subm_user_id_19c023_idx')],
            },
        ),
    ]
